In [10]:
import numpy as np
ar=np.random.randint(20,size=(4,5))
print(ar)

[[19 14  7  1  8]
 [ 3 14  5  8  9]
 [15  7 11  8  3]
 [19  7 15  6  7]]


In [2]:
print("Mean:",ar.mean(axis=1))
print("Standard deviation:",ar.std(axis=1))
print("Variance:", ar.var(axis=1))

Mean: [6.6 7.4 6.  6.6]
Standard deviation: [3.92937654 4.22374242 5.5136195  3.92937654]
Variance: [15.44 17.84 30.4  15.44]


In [3]:
b=np.array([56,48,22,41,78,91,24,46,8,33])
a=np.array([56,48,22,41,78,91,24,46,8,33])
b.sort()
print(a)
print(b)
for i in range(len(a)):
    print(a[i],"is at index:",end=" ")
    for j in range(len(b)):
        if(a[i]==b[j]):
            print(j)
            print()


[56 48 22 41 78 91 24 46  8 33]
[ 8 22 24 33 41 46 48 56 78 91]
56 is at index: 7

48 is at index: 6

22 is at index: 1

41 is at index: 4

78 is at index: 8

91 is at index: 9

24 is at index: 2

46 is at index: 5

8 is at index: 0

33 is at index: 3



In [4]:
n=int(input("Enter number of Rows:"))
m=int(input("Enter number of Columns:"))
arr=np.random.randint(n*m,size=(n,m))
print(arr)
print("The shape of the array is:", arr.shape)
print("The array is of data type:",arr.dtype)
print("the type of aray is:", type(arr))
arrt=arr.reshape(m,n)
print("The reshaped array is:")
print(arrt)

Enter number of Rows:6
Enter number of Columns:3
[[ 9 13  0]
 [11  5  0]
 [ 1 12 17]
 [15  5 12]
 [ 9  7  7]
 [11  5  9]]
The shape of the array is: (6, 3)
The array is of data type: int64
the type of aray is: <class 'numpy.ndarray'>
The reshaped array is:
[[ 9 13  0 11  5  0]
 [ 1 12 17 15  5 12]
 [ 9  7  7 11  5  9]]


In [12]:
x=np.array([1,2,3,0,8,np.nan,0,5,7,np.nan])
print(x)
z=[]
nz=[]
na=[]
ns=np.isnan(x)
for i in range(len(x)):
    if x[i]==0:
        z.append(i)
    elif ns[i]:
        na.append(i)
    else:
        nz.append(i)
print(z)
print(nz)
print(na)

[ 1.  2.  3.  0.  8. nan  0.  5.  7. nan]
[3, 6]
[0, 1, 2, 4, 7, 8]
[5, 9]
